version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_TAG=$(git rev-parse --short HEAD)
      - export TZ="Asia/Tokyo"

  build:
    commands:
      - cd docker
      - docker build -t autoscale-test-repo:${IMAGE_TAG} .
      - docker tag autoscale-test-repo:${IMAGE_TAG} $(AWS_ACCOUNT_ID).dkr.ecr.ap-northeast-1.amazonaws.com/autoscale-test-repo:${IMAGE_TAG}

  post_build:
    commands:
      - docker push $(AWS_ACCOUNT_ID).dkr.ecr.ap-northeast-1.amazonaws.com/autoscale-test-repo:${IMAGE_TAG}